import os

BOT_TOKEN = os.getenv("BOT_TOKEN")
ENV = "DEV"

LM_OPENAI_API_KEY = os.getenv("LM_OPENAI_API_KEY")
LM_EXAFUNCTION_API_KEY = os.getenv("LM_EXAFUNCTION_API_KEY")
LM_AI21_API_KEY = os.getenv("LM_AI21_API_KEY")
LM_COHERE_API_KEY = os.getenv("LM_COHERE_API_KEY")

IFTTT_KEY = os.getenv("IFTTT_KEY")
